### ISSUE TITLE
Missing clicks on spells

### ISSUE THREAD

**Issue by KawhiNot** [SirOlaf/wizsprinter#5]
there is no error for it, all that happens is I say for it to potent enchant a feint, it will attemp to click the potent to enchant the feint(p1) but it won't actually click it while all that is happening on the other 2 clients(p2 and p3) it manages to cast spells, so because on this one client it misses it also uncasts the spells on the other 2 clients, while also not casting the spell on p1 and it just idles until it the next round, now sometimes that also can happen on the second round, causing the clients to either go idle and the script to crash or them to die resulting in a crash

**Comment by SirOlaf** [comment]
Should be fixed in 240a9f3
