### ISSUE TITLE
'NamedSpell' object has no attribute 'optional'

### ISSUE THREAD

**Issue by KawhiNot** [SirOlaf/wizsprinter#7]
Get this issue when trying to enchant a spell, I tried with both a shadow spell and a normal spell had the same problem, on occasion it selects the epic to enchant the spell and on occasion it doesn't select the epic.
![image](https://user-images.githubusercontent.com/65625755/174492487-0d385a5d-5ff4-4eee-8ac2-1395e9987062.png)

**Comment by SirOlaf** [comment]
Fixed in 5530eaf
